<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Featured_model extends CI_Model
{
  public $table = 'featured';
  public $id    = 'id_featured';
  public $order = 'ASC';

  // get all
  function get_all()
  {
    $this->db->order_by('no_urut');
    $this->db->from($this->table);
    $this->db->join('berita', 'berita.id_berita = featured.judul_featured');
    return $this->db->get()->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->row();
  }

  // get total rows
  function total_rows() 
  {
    return $this->db->get($this->table)->num_rows();
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

}

/* End of file Featured_model.php */
/* Location: ./application/models/Featured_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */