<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Komentar_model extends CI_Model
{
  public $table = 'komentar';
  public $id    = 'id_komentar';
  public $order = 'DESC';

  // get all
  function get_all()
  {
    $this->db->where('status','ya');
    $this->db->order_by('time_verif');
    $this->db->join('komentar', 'berita.id_berita = komentar.id_berita');
    return $this->db->get('berita')->result();
  }

  function get_all_komentar_pending()
  {
    $this->db->where('status','tidak');
    $this->db->order_by($this->id, $this->order);
    $this->db->join('komentar', 'berita.id_berita = komentar.id_berita');
    return $this->db->get('berita')->result();
  }

  function get_total_row_kategori()
  {
    $this->db->where('status','ya');
    return $this->db->get($this->table)->num_rows();
  }

  function get_total_row_kategori_pending()
  {
    $this->db->where('status','tidak');
    return $this->db->get($this->table)->num_rows();
  }

  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->row(); 
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function terima($id, $data)
  {
    $this->db->where($this->id,$id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

}

/* End of file Komentar_model.php */
/* Location: ./application/models/Komentar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */